import express from "express";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '10mb' }));

  // API Route for Card Generation
  app.post("/api/generate-card", async (req, res) => {
    const { characterName } = req.body;
    // Check both GEMINI_API_KEY (default) and API_KEY (selected via dialog)
    const apiKey = process.env.GEMINI_API_KEY || process.env.API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: "Gemini API Key not configured. Please add it to your environment or select it using the key dialog." });
    }

    if (!characterName) {
      return res.status(400).json({ error: "Character name is required." });
    }

    try {
      console.log(`Generating card for: ${characterName}`);
      const ai = new GoogleGenAI({ apiKey });
      
      const generateWithModel = async (modelName: string) => {
        console.log(`Attempting generation with model: ${modelName}`);
        return await ai.models.generateContent({
          model: modelName,
          contents: {
            parts: [
              {
                text: `You are a master anime card designer.
                1. Create a long, detailed artistic prompt for a high-quality anime character trading card of "${characterName}". 
                Use high-key lighting, minimal black colors, and an aesthetic/pastel palette. 
                The description should be evocative, describing the character's pose, the background, the lighting, and the overall vibe.
                
                2. Based on this description, determine a Power Level (between 1 and 9999) and a Strength Rating (between 1 and 1000) that accurately reflects their lore.
                
                Return the description and stats as a JSON string in the text part, and also generate the image.
                JSON format: {"description": "...", "power": 8500, "strength": 750}`
              }
            ]
          },
          config: {
            imageConfig: {
              aspectRatio: "3:4",
              imageSize: "1K"
            }
          }
        });
      };

      let response;
      try {
        // Try high-quality model first
        response = await generateWithModel('gemini-3.1-flash-image-preview');
      } catch (e: any) {
        console.warn("Primary model failed, trying fallback:", e.message);
        // Fallback to more widely available model
        response = await generateWithModel('gemini-2.5-flash-image');
      }

      console.log("Gemini response received");
      let imageUrl = '';
      let metadata = { description: '', power: 1000, strength: 500 };

      if (!response.candidates || response.candidates.length === 0) {
        throw new Error("No response generated by Gemini. This might be due to safety filters or an invalid prompt.");
      }

      const parts = response.candidates[0].content?.parts || [];
      
      for (const part of parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          console.log("Image part found");
        } else if (part.text) {
          console.log("Text part found");
          try {
            const jsonMatch = part.text.match(/\{[\s\S]*\}/);
            if (jsonMatch) {
              metadata = JSON.parse(jsonMatch[0]);
            }
          } catch (e) {
            console.error("Failed to parse metadata JSON", e);
          }
        }
      }

      if (!imageUrl) {
        console.error("No image data in response parts. Parts received:", parts.map(p => p.text ? 'text' : 'data').join(', '));
        throw new Error("Gemini generated text but failed to generate the image. This can happen if the character name is flagged by safety filters or if the model is overloaded.");
      }

      res.json({
        imageUrl,
        raw_power: metadata.power || 1000,
        strength: metadata.strength || 500,
        prompt_text: metadata.description || `A high-quality, aesthetic anime trading card of ${characterName}.`
      });
    } catch (error: any) {
      console.error("Gemini Generation Error:", error);
      
      // Check for specific API key errors
      const errorMessage = error.message || "";
      if (errorMessage.includes("API key not valid") || errorMessage.includes("invalid API key")) {
        return res.status(401).json({ 
          error: "Invalid API Key. Please check your Gemini API key configuration.",
          code: "INVALID_API_KEY"
        });
      }

      res.status(500).json({ 
        error: error.message || "Failed to generate card.",
        details: process.env.NODE_ENV === 'development' ? error.stack : undefined
      });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
    app.get("*", (req, res) => {
      res.sendFile("dist/index.html", { root: "." });
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
